apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber
spec:
  template:
    spec:
      containers:
      - name: service
        image: gcr.io/ucdlib-pubreg/fin-base-service:local-dev
        env:
        - name: K8S_ENABLED
          value: "true"
        - name: "K8S_NAMESPACE"
          value: "dams"
        - name : "K8S_PLATFORM"
          value: "docker-desktop"
        - name: K8S_COLLECTION_IMPORT_IMAGE
          value: gcr.io/ucdlib-pubreg/fin-base-service:local-dev
        - name: K8S_COLLECTION_IMPORT_URL
          value: http://gateway:3000
        - name: K8S_COLLECTION_IMPORT_LOCAL_DEV_HOST_PATH
          value: ""
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig