kind: Deployment
metadata:
  name: dbsync
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:2.4.10
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: 'true'
      nodeSelector:
        intendedfor: scalable-pool
