kind: Deployment
metadata:
  name: dbsync
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:2.2.0
          env:
          - name: FIN_METRICS_EXPORT_GC
            value: "true"