apiVersion: batch/v1
kind: Job
metadata:
  name: import-amerine-menus
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: amerine-menus
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-amerine-menus-volume-claim