apiVersion: batch/v1
kind: Job
metadata:
  name: import-california-here-we-come-travelogue
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: california-here-we-come-travelogue
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-california-here-we-come-travelogue-volume-claim