kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-california-here-we-come-travelogue-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 9Gi