apiVersion: batch/v1
kind: Job
metadata:
  name: import-medical-pathology-oral-histories
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: medical-pathology-oral-histories
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-medical-pathology-oral-histories-volume-claim