kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-medical-pathology-oral-histories-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1.9Gi