apiVersion: batch/v1
kind: Job
metadata:
  name: import-japanese-american-woman-postwar-california
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: japanese-american-woman-postwar-california
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-japanese-american-woman-postwar-california-volume-claim