kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-japanese-american-woman-postwar-california-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 2Gi