apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: 'true'
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-iipimage-server:2.3.21
      serviceAccountName: dams-production
