serviceAccount:
  create: true
  name: fluent-bit

env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/fin/service-account.json

config:
  inputs: |
    [INPUT]
        name          kubernetes_events
        tag           kube_events

    [INPUT]
        Name        tail
        Tag_Regex   var.log.containers.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Tag         kube_logs.<namespace_name>.<pod_name>.<container_name>
        Path        /var/log/containers/*.log
        Parser      docker
        DB          /var/log/fluent-bit-k8s-container.db
  filters: |
    [FILTER]
        Name              parser
        Match             kube_logs.*
        Key_Name          log
        Parser            log_json_extractor

    # Parse the inner Bunyan JSON after extracting it
    [FILTER]
        Name              parser
        Match             kube_logs.*
        Key_Name          extracted_log
        Parser            json_ucdlib


    [FILTER]
        Name              modify
        Match             kube_logs.*
        Remove            container_name

    [FILTER]
        Name              modify
        Match             kube_logs.*
        Condition         Key_does_not_exist severity
        Condition         Key_value_matches log ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.*\s+stderr\s+F.*
        Set               severity ERROR

    [FILTER]
        Name              modify
        Match             kube_logs.*
        Condition         Key_does_not_exist severity
        Condition         Key_value_matches log ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.*\s+stdout\s+F.*
        Set               severity INFO


  outputs: |
    [OUTPUT]
        Name        stackdriver
        resource    k8s_container
        Match       kube_logs.*
        tag_prefix  kube_logs.
        k8s_cluster_name dams-v2-dev
        k8s_cluster_location  uc-davis-lib
        severity_key severity
    
    [OUTPUT]
        Name        stackdriver
        resource    k8s_container
        Match       kube_events.*
        tag_prefix  kube_events.
        k8s_cluster_name dams-v2-dev
        k8s_cluster_location  uc-davis-lib

  customParsers: |
    # Extracts the JSON log content from the 'log' field
    [PARSER]
        Name   log_json_extractor
        Format regex
        Regex  ^[^ ]+ [^ ]+ [^ ]+ (?<extracted_log>\{.*\})$
    
    # Parses the extracted Bunyan JSON
    [PARSER]
        Name   json_ucdlib
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

extraVolumeMounts:
  - name: service-account
    mountPath: /etc/fin/service-account.json
    subPath: service-account.json

extraVolumes:
  - name: service-account
    secret:
      secretName: service-account