apiVersion: batch/v1
kind: Job
metadata:
  name: import-ag-eng
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: ag-eng
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-ag-eng-volume-claim