version: '3'

###
# Fin Server from deployed DockerHub container images
###
services:

  ###
  # Front end apache server for proxying to gateway from host port
  ###
  lb:
    image: gcr.io/ucdlib-pubreg/fin-apache-lb:sandbox
    ports:
      - ${HOST_PORT:-3000}:80
    restart: unless-stopped

  ###
  # Font End NodeJS Application Server
  ###
  gateway:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - fedora-data:/data
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=gateway
    depends_on:
      - fcrepo
      - redis
      - elasticsearch
    restart: unless-stopped
    command: npm run gateway

  ###
  # Fedora Repository
  ###
  fcrepo:
    image: gcr.io/ucdlib-pubreg/fin-fcrepo:sandbox
    ports:
      - ${FCREPO_HOST_PORT:-8080}:8080
    volumes:
      - fedora-data:/usr/local/tomcat/fcrepo-home/data
      - activemq-data:/usr/local/tomcat/ActiveMQ
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    restart: unless-stopped

  ###
  # Fedora Postgres Service
  ###
  postgres:
    image: gcr.io/ucdlib-pubreg/fin-postgres:sandbox
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  ###
  # Fin Init Service
  ###
  init:
    image: gcr.io/ucdlib-pubreg/dams-init:sandbox
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=init

  ###
  # Session, admin store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo

  ###
  # RabbitMQ - for messaging
  ###
  rabbitmq:
    image: gcr.io/ucdlib-pubreg/fin-rabbitmq:sandbox
    ports:
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  ###
  # Fin uber utils service - lots of small tasks
  ###
  uber:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - fs-tests:/fs-tests
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=uber
      - FIN_METRICS_FS_ENABLED=true
      - FIN_METRICS_FIN_ENABLED=true
      - FIN_METRICS_FCREPO_ENABLED=true
    depends_on:
      - elasticsearch
    restart: unless-stopped
    command: npm run uber


  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=ucd-lib-client
    depends_on:
      - elasticsearch
    restart: unless-stopped
    command: node ucd-lib-client/index.js

  ###
  # External Database Sync Service
  ###
  dbsync:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=dbsync
    depends_on:
      - gateway
    restart: unless-stopped
    command: npm run dbsync

  ###
  # GCS - Access & Sync
  ###
  gcs:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
      - gcs-disk-cache:/etc/gcs-disk-cache
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=gcs
    depends_on:
      - gateway
    restart: unless-stopped
    command: npm run gcs

  ###
  # Search
  ###
  elasticsearch:
    image: gcr.io/ucdlib-pubreg/fin-elastic-search:sandbox
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    depends_on:
      - fcrepo

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - ${KIBANA_HOST_PORT:-5601}:5601
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
      - telemetry.enabled=false
    depends_on:
      - elasticsearch
    restart: unless-stopped

  ###
  # Fin Workflows
  ###
  workflow:
    image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=workflow
    depends_on:
      - gateway
    restart: unless-stopped
    command: node workflow/index.js


  iiif:
    image: gcr.io/ucdlib-pubreg/dams-iipimage-server:sandbox
    privileged: true
    # cap_add:
    #   - SYS_ADMIN
    # devices:
    #   - /dev/fuse
    # security_opt:
    #   - seccomp:unconfined
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/fin/service-account.json
      - FUSE_DIR=/etc/gcs-fuse/fcrepo/rest
      - GCS_BUCKET=dams-client-media-dev
      - VERBOSITY=5
      - FIN_SERVICE_NAME=iiif
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
      - gcs-fuse:/etc/gcs-fuse
    ports:
      - 9000:9000
    # command: bash -c "tail -f /dev/null"

  pg-rest:
    image: gcr.io/ucdlib-pubreg/fin-pg-rest:sandbox
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
    env_file:
      - .env
    environment:
      - FIN_SERVICE_NAME=pg-rest
    # command: bash -c "tail -f /dev/null"

###
# Docker data volumes
###
volumes:
  fs-tests:
    driver: local
  fedora-data:
    driver: local
  activemq-data:
    driver: local
  pg-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  gcs-fuse:
    driver: local
  gcs-disk-cache:
    driver: local
  rabbitmq-data:
    driver: local