apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:sandbox
          env:
          - name: IMAGE_UTILS_SERVICE_CONTAINER
            value: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-image-utils:jm-image-workflow-v2
          - name: WORKFLOW_ENV
            value: sandbox
          - name: IMAGE_UTILS_SERVICE_URL
            value: https://dams-image-utils-sandbox-fga4yw7psa-uc.a.run.app
          - name: GCS_CLIENT_MEDIA_BUCKET
            value: dams-client-media-sandbox
