apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:sandbox
          env:
          - name: IMAGE_UTILS_SERVICE_CONTAINER
            value: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-image-utils:2.4.22
