apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-rest
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-pg-rest:2.11.8
