kind: Deployment
metadata:
  name: workflow
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
          # command: ["/bin/sh", "-c", "tail -f /dev/null"]
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: "true"
