apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucd-lib-client
spec:
  selector:
    matchLabels:
      app: ucd-lib-client
  template:
    metadata:
      labels:
        app: ucd-lib-client
    spec:
      containers:
      - name: service
        image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:sandbox
        imagePullPolicy: Always
        command: ["node", "ucd-lib-client/index.js"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: FIN_METRICS_FIN_ENABLED
          value: "true"
        - name: FIN_METRICS_FCREPO_ENABLED
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/fin/service-account.json
        volumeMounts:
        - name: service-account
          mountPath: /etc/fin/service-account.json
          subPath: service-account.json
        - name: env-config
          mountPath: /etc/fin/.env
          subPath: .env
      volumes:
      - name: service-account
        secret:
          secretName: service-account
      - name: env-config
        secret:
          secretName: env-config