kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:2.1.4
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: "true"
            - name: FCREPO_RO_ENABLED
              value: "true"
            - name: FIN_GATEWAY_HTTPS_ENABLED
              value: "true"
            - name: K8S_ENABLED
              value: "true"
            - name : "K8S_PLATFORM"
              value: "gke"
            - name: "K8S_CLUSTER"
              value: "dams"
            - name: "K8S_REGION"
              value: "us-west1-b"