apiVersion: batch/v1
kind: Job
metadata:
  name: import-ag-teaching-aids
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: ag-teaching-aids
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-ag-teaching-aids-volume-claim