apiVersion: batch/v1
kind: Job
metadata:
  name: import-greene-papers
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: greene-papers
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-greene-papers-volume-claim