apiVersion: batch/v1
kind: Job
metadata:
  name: import-tibbetts-photo
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: tibbetts-photo
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-tibbetts-photo-volume-claim