apiVersion: batch/v1
kind: Job
metadata:
  name: import-glen-alpine
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: glen_alpine
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-glen-alpine-volume-claim