apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fcrepo
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-fcrepo:2.11.3
