kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
          # command: ["bash", "-c", "tail -f /dev/null"]
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: "true"
            - name: FCREPO_RO_ENABLED
              value: "true"
            - name: FIN_GATEWAY_HTTPS_ENABLED
              value: "true"
          volumeMounts:
            - mountPath: /etc/fin/certs/sandbox.dams.library.ucdavis.edu
              name: dams-ssl
      nodeSelector:
        intendedfor: scalable-pool
      volumes:
        - name: dams-ssl
          secret:
            secretName: dams-ssl
