apiVersion: v1
kind: Service
metadata:
  name: gateway-ingress
  annotations:
    # Use external passthrough load balancer
    # https://cloud.google.com/kubernetes-engine/docs/how-to/external-svc-lb-rbs
    # https://cloud.google.com/load-balancing/docs/passthrough-network-load-balancer
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  loadBalancerIP : "35.238.136.107"
  # Use local traffic policy to preserve client source IP
  externalTrafficPolicy: Local
  selector:
    app: gateway
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3443