apiVersion: batch/v1
kind: Job
metadata:
  name: import-trafton-crane
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: trafton-crane
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-trafton-crane-volume-claim