apiVersion: batch/v1
kind: Job
metadata:
  name: import-lug-labels
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: lug_labels
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-lug-labels-volume-claim