kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:2.7.17
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: 'true'
      nodeSelector:
        intended-for: digital-dev-frontend
