kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:2.6.6
          env:
            - name: FIN_METRICS_EXPORT_GC
              value: 'true'
