apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

patches:
  - path: service.yaml
    target:
      kind: Service
      name: gateway
  - path: deployment.yaml
    target:
      kind: Deployment