apiVersion: batch/v1
kind: Job
metadata:
  name: import-yearbooks
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: yearbooks
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-yearbooks-volume-claim