apiVersion: batch/v1
kind: Job
metadata:
  name: import-lantern-slides
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: lantern_slides
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-lantern-slides-volume-claim