apiVersion: batch/v1
kind: Job
metadata:
  name: import-postcards
spec:
  template:
    spec:
      containers:
      - name: importer
        command: ["/bin/bash", "-c", "tail -f /dev/null"]
        env:
          - name: COLLECTION_NAME
            value: postcards
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-postcards-volume-claim