kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-amerine-menus-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 175Gi