apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      storageClassName: nfs-csi
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi