apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: service
        command: ["npm", "run", "gateway"]
        env:
        - name: FIN_SERVICE_NAME
          value: "gateway"
        - name: ADMIN_UI_EXTENSIONS_ENABLED
          value: "true"
        - name: ADMIN_UI_EXTENSIONS_SOURCE_PATH
          value: "/fin/admin/js/dams-admin-ui-ext.js"
        - name: ADMIN_UI_EXTENSIONS_ROUTES
          value: "collection-import:dams-collection-import"
      nodeSelector:
        intendedfor: scalable-pool