apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-rabbitmq:2.8.0
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      storageClassName: nfs-csi
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi