apiVersion: batch/v1
kind: Job
metadata:
  name: import-aerial-photos
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: aerial-photos
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-aerial-photos-volume-claim