apiVersion: batch/v1
kind: Job
metadata:
  name: import-pullman-saloon
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: pullman-saloon
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-pullman-saloon-volume-claim