apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"  
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
          env:
          - name: K8S_ENABLED
            value: "true"
          - name : "K8S_PLATFORM"
            value: "gke"
          - name: "K8S_CLUSTER"
            value: "dams"
          - name: "K8S_REGION"
            value: "us-central1-a"
          - name: K8S_COLLECTION_IMPORT_IMAGE
            value: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
          volumeMounts:
          - name: gcs-kustomize-templates-fuse
            mountPath: /etc/fin/k8s-templates
      volumes:
      - name: gcs-kustomize-templates-fuse
        persistentVolumeClaim:
          claimName: gcs-kustomize-templates-pvc
      serviceAccountName: dams-production