apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-kustomize-templates-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: gcs-storage-class
  claimRef:
    namespace: default
    name: gcs-kustomize-templates-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: dams-kustomize-templates