apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-kustomize-templates-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: gcs-kustomize-templates-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: gcs-storage-class