apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gcs-pv.yaml
  - gcs-pvc.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: uber
