apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fcrepo-ro
spec:
  template:
    spec:
      containers:
      - name: service
        image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-fcrepo:2.8.0
