apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber
spec:
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: service
        command: ["npm", "run", "uber"]
        env:
        - name: FIN_SERVICE_NAME
          value: "uber"
        - name: FIN_METRICS_FS_ENABLED
          value: "true"
        - name: FIN_METRICS_EXPORT_GC
          value: "true"
        - name: FIN_METRICS_FS_ENABLED
          value: "true"
        - name: FIN_METRICS_FIN_ENABLED
          value: "false"
        volumeMounts:
        - name: fs-tests-volume
          mountPath: /fs-tests
        ports:
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003
        - containerPort: 3004
        readinessProbe:
          httpGet:
            port: 3004 # check api endpoint
      volumes:
      - name: fs-tests-volume
        emptyDir: {}