apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          image: >-
            us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-elastic-search:2.12.0
