apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
        - image: gcr.io/ucdlib-pubreg/fin-elastic-search:sandbox
