apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: import
spec:
  selector:
    matchLabels:
      app: import
  replicas: 1
  template:
    metadata:
      labels:
        app: import
    spec:
      containers:
      - name: importer
        imagePullPolicy: Always
        image: gcr.io/ucdlib-pubreg/dams-base-service:sandbox
        command: ["/bin/sh", "-c", "tail -f /dev/null"]  
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/fin/service-account.json
        volumeMounts:
        - name: service-account
          mountPath: /etc/fin/service-account.json
          subPath: service-account.json
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: service-account
        secret:
          secretName: service-account
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi