apiVersion: batch/v1
kind: Job
metadata:
  name: import-kearney-tea-project
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: kearney-tea-project
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-kearney-tea-project-volume-claim