apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fcrepo
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-fcrepo:2.13.0
      volumes:
        - name: ocfl-volume
          gcePersistentDisk:
            pdName: ocfl-volume-v2
            fsType: ext4
  volumeClaimTemplates:
    - metadata:
        name: activemq-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi