apiVersion: batch/v1
kind: Job
metadata:
  name: import-davis-scouts
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: davis-scouts
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-davis-scouts-volume-claim