apiVersion: batch/v1
kind: Job
metadata:
  name: import-mckinnon-ruble
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: mckinnon-ruble
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-mckinnon-ruble-volume-claim