apiVersion: v1
kind: Service
metadata:
  name: ingress-test
spec:
  type: LoadBalancer
  loadBalancerIP : "35.222.237.103"
  selector:
    app: gateway
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3443