apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress-lb-service.yaml
- ingress-test.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment