apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          image: >-
            us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-elastic-search:2.13.0
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
