apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-base-service:sandbox
