kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-hall-ada-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi