apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: import-robinson
spec:
  selector:
    matchLabels:
      app: import-robinson
  template:
    metadata:
      labels:
        app: import-robinson
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: robinson
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 235Gi