apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 3
  template:
    spec:
      nodeSelector: null
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intended-for
                    operator: In
                    values:
                      - digital-dev-frontend
                      - es-quorum
      containers:
        - name: elasticsearch
          image: >-
            us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-elastic-search:2.14.0
          env:
            - name: cluster.initial_master_nodes
              value: elasticsearch-0,elasticsearch-1,elasticsearch-2
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
