apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-elastic-search:dev
