kind: Deployment
metadata:
  name: init
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-init:sandbox
          # command: ["bash", "-c", "tail -f /dev/null"]
