apiVersion: batch/v1
kind: Job
metadata:
  name: import-video-demo
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: video-demo
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-video-demo-volume-claim