version: '3'

###
# Fin Server from deployed DockerHub container images
###
services:

  ###
  # Front end apache server for proxying to gateway from host port
  ###
  lb:
    image: {{LB_IMAGE_NAME}}:{{FIN_TAG}}
    ports:
      - ${HOST_PORT:-3000}:80

  ###
  # Front End NodeJS Application Server
  ###
  gateway:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - fedora-data:/data
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/admin-ui/config.js:/fin/services/admin-ui/config.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/admin-ui/controllers:/fin/services/admin-ui/controllers
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/admin-ui/client/public/index.html:/fin/services/admin-ui/client/public/index.html
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/admin-ui/client/public/src:/fin/services/admin-ui/client/public/src
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/admin-ui/client/public/elements:/fin/services/admin-ui/client/public/elements
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    depends_on:
      - fcrepo
      - redis
      - elasticsearch
    command: npm run gateway
    # command: bash -c 'tail -f /dev/null'

  ###
  # Fedora Repository
  ###
  fcrepo:
    image: {{DAMS_FCREPO_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    ports:
      - 8080:8080
    # Example for change logging.  Note, don't forget to still include the fcrepo.properties file location!
    # See: https://wiki.lyrasis.org/display/FEDORA6x/Logging
    # environment:
    #  - CATALINA_OPTS=-Dfcrepo.log.auth=DEBUG -Dfcrepo.config.file=/etc/fin/fcrepo.properties
    volumes:
      - fedora-data:/usr/local/tomcat/fcrepo-home/data
      - activemq-data:/usr/local/tomcat/ActiveMQ
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fcrepo/activemq.xml:/usr/local/tomcat/webapps/fcrepo/WEB-INF/classes/config/activemq.xml
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fcrepo/fcrepo.properties:/etc/fin/fcrepo.properties
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fcrepo/root-authorization.ttl:/etc/fin/root-authorization.ttl
    env_file:
      - .env

  ###
  # Fedora Postgres Service
  ###
  postgres:
    image: {{POSTGRES_IMAGE_NAME}}:{{FIN_TAG}}
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

  ###
  # Fin Init Service
  ###
  init:
    image: {{UCD_DAMS_INIT_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/init/postgres:/etc/ucdlib-service-init/postgres
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/init/fcrepo:/etc/ucdlib-service-init/fcrepo
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/postgres/003-fin-cache.sql:/etc/ucdlib-service-init/postgres/003-fin-cache.sql
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/fcrepo/application:/etc/ucdlib-service-init/fcrepo/application
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/fcrepo/collection:/etc/ucdlib-service-init/fcrepo/collection
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/fcrepo/fin:/etc/ucdlib-service-init/fcrepo/fin
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/fcrepo/item:/etc/ucdlib-service-init/fcrepo/item
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/init/fcrepo/service:/etc/ucdlib-service-init/fcrepo/service
    env_file:
      - .env

  ###
  # Session, admin store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo

  ###
  # UC DAMS Client API
  ###
  api:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    depends_on:
      - elasticsearch
    command: npm run api
  # command: bash -c 'tail -f /dev/null'

  finac:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/fin-ac:/fin/services/fin-ac
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    command: node fin-ac/index.js
    # command: bash -c 'tail -f /dev/null'

  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/index.js:/fin/services/ucd-lib-client/index.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/config.js:/fin/services/ucd-lib-client/config.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/elements:/fin/services/ucd-lib-client/client/public/elements
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/fonts:/fin/services/ucd-lib-client/client/public/fonts
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/images:/fin/services/ucd-lib-client/client/public/images
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/lib:/fin/services/ucd-lib-client/client/public/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/loader:/fin/services/ucd-lib-client/client/public/loader
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/index.html:/fin/services/ucd-lib-client/client/public/index.html
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/public/manifest.json:/fin/services/ucd-lib-client/client/public/manifest.json
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/babel.config.js:/fin/services/ucd-lib-client/client/babel.config.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/watch.sh:/fin/services/ucd-lib-client/client/watch.sh
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/build.sh:/fin/services/ucd-lib-client/client/build.sh
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/webpack-dist.config.js:/fin/services/ucd-lib-client/client/webpack-dist.config.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/client/webpack.config.js:/fin/services/ucd-lib-client/client/webpack.config.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/controllers:/fin/services/ucd-lib-client/controllers
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/lib:/fin/services/ucd-lib-client/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/ucd-lib-client/model:/fin/services/ucd-lib-client/model
    env_file:
      - .env
    depends_on:
      - elasticsearch
    command: node ucd-lib-client/index.js
    # command: bash -c 'tail -f /dev/null'

  ###
  # External Database Sync Service
  ###
  dbsync:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    depends_on:
      - gateway
    command: npm run dbsync
    # command: bash -c 'tail -f /dev/null'

  ###
  # ES Index Management Service
  ###
  es-index-management:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/es-index-management:/fin/services/es-index-management
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    depends_on:
      - gateway
    command: npm run es-index-management

  ###
  # GCS - Sccess & Sync
  ###
  gcs:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - gcs-disk-cache:/etc/gcs-disk-cache
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gcs/lib:/fin/services/gcs/lib
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gcs/index.js:/fin/services/gcs/index.js
    env_file:
      - .env
    depends_on:
      - gateway
    command: npm run gcs
    # command: bash -c 'tail -f /dev/null'

  ###
  # Search
  ###
  elasticsearch:
    image: {{ELASTIC_SEARCH_IMAGE_NAME}}:{{FIN_TAG}}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
      - .env
    volumes:
      - es-data:/usr/share/elasticsearch/data
    depends_on:
      - fcrepo
    # command: bash -c 'tail -f /dev/null'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - 5601:5601
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
      - telemetry.enabled=false
    depends_on:
      - elasticsearch

  ###
  # Fin Workflows
  ###
  workflow:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/lib:/fin/services/node-utils/lib
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/config.js:/fin/services/node-utils/config.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/index.js:/fin/services/node-utils/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/workflow/index.js:/fin/services/workflow/index.js
    env_file:
      - .env
    depends_on:
      - gateway
    command: npm run workflow
    # command: bash -c 'tail -f /dev/null'

  ###
  # Image Utils OCR Services
  ###
  image-utils:
    image: {{IMAGE_UTILS_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/lib:/fin/services/node-utils/lib
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/config.js:/fin/services/node-utils/config.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils/index.js:/fin/services/node-utils/index.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/image-utils/index.js:/fin/services/image-utils/index.js
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/image-utils/cli:/fin/services/image-utils/cli
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/image-utils/controllers:/fin/services/image-utils/controllers
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/image-utils/lib:/fin/services/image-utils/lib
    env_file:
      - .env
    depends_on:
      - gateway
    ports:
      - 8082:3000
    # command: bash -c 'tail -f /dev/null'

  ###
  # OIDC AuthenticationService
  ###
  oidc:
    image: {{UCD_DAMS_SERVER_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/api:/fin/services/api
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/oidc:/fin/services/oidc
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/dbsync:/fin/services/dbsync
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/gateway:/fin/services/gateway
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/fin/node-utils:/fin/services/node-utils
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/index.js:/fin/api/index.js
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/fin-api/lib:/fin/api/lib
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/fin/models:/fin/services/models
    env_file:
      - .env
    depends_on:
      - gateway
    # command: bash -c 'tail -f /dev/null'
    command: npm run oidc
    
  keycloak:
    image: {{KEYCLOAK_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME: localhost
    volumes:
      - ../keycloak/dams-local-dev-realm.json:/opt/keycloak/data/import/dams-local-dev-realm.json
    ports:
      - 8081:8080
      - 8443:8443
    command: ["start-dev --import-realm"]

  iiif:
    image: {{IIIF_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/fin/service-account.json
      - FUSE_DIR=/etc/gcs-fuse/fcrepo/rest
      - GCS_BUCKET=dams-client-media-dev
      - VERBOSITY=5
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/iipimage/setup-gcsfuse.sh:/etc/iipimage-server/setup-gcsfuse.sh
      - ../{{REPOSITORY_DIR}}/{{UCD_DAMS_REPO_NAME}}/services/iipimage/start.sh:/etc/iipimage-server/start.sh
      - gcs-fuse:/etc/gcs-fuse
    ports:
      - 9000:9000
    # command: bash -c "tail -f /dev/null"

  pg-rest:
    image: {{PGREST_IMAGE_NAME}}:{{DOCKER_CACHE_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-../service-account.json}:/etc/fin/service-account.json
      - ../{{REPOSITORY_DIR}}/{{FIN_SERVER_REPO_NAME}}/services/pg-rest/start.sh:/start.sh
    env_file:
      - .env
    # command: bash -c "tail -f /dev/null"

###
# Docker data volumes
###
volumes:
  fedora-data:
    driver: local
  activemq-data:
    driver: local
  pg-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  gcs-fuse:
    driver: local
  gcs-disk-cache:
    driver: local