apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fcrepo-ro
spec:
  selector:
    matchLabels:
      app: fcrepo-ro
  replicas: 2
  template:
    metadata:
      labels:
        app: fcrepo-ro
    spec:
      containers:
      - name: service
        imagePullPolicy: Always
        image: gcr.io/ucdlib-pubreg/fin-fcrepo:sandbox
        volumeMounts:
        - name: ocfl-volume
          mountPath: /usr/local/tomcat/fcrepo-home/data
          # readOnly: true
        - name: activemq-volume
          mountPath: /usr/local/tomcat/ActiveMQ
        resources:
          requests:
            memory: "6Gi"
            cpu: "1"
        env:
        - name: CATALINA_OPTS
          value: "-Dfcrepo.config.file=/etc/fin/fcrepo.properties -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xms1G -Xmx4G -XX:+UseG1GC -XX:+DisableExplicitGC"
        ports:
        - containerPort: 8080
      nodeSelector:
        intendedfor: scalable-pool
      volumes:
      - name: ocfl-volume
        persistentVolumeClaim:
          claimName: ocfl-volume-claim
  volumeClaimTemplates:
    - metadata:
        name: activemq-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi