apiVersion: batch/v1
kind: Job
metadata:
  name: import-sherry-lehmann
spec:
  template:
    spec:
      containers:
      - name: importer
        # command: ["/bin/bash", "-c", "tail -f /dev/null"]  
        env:
          - name: COLLECTION_NAME
            value: sherry-lehmann
          - name: IGNORE_BINARY_SYNC
            value: "true"
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-sherry-lehmann-volume-claim