kind: Deployment
metadata:
  name: gcs
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-base-service:dev
          env:
          - name: FIN_METRICS_EXPORT_GC
            value: "true"