apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.4.3
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        # - name: SERVER_BASEPATH
        #   value: /kibana
        # - name: SERVER_REWRITEBASEPATH
        #   value: "true"
        - name: xpack.security.enabled
          value: "false"
        - name: telemetry.enabled
          value: "false"