apiVersion: batch/v1
kind: Job
metadata:
  name: import-greek-bibles
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: greek_bibles
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-greek-bibles-volume-claim