apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-kustomize-templates-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: gcs-kustomize-templates-pv
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi