apiVersion: batch/v1
kind: Job
metadata:
  name: import-sherry-lehmann
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: sherry-lehmann
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-sherry-lehmann-volume-claim