apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-mirror
spec:
  selector:
    matchLabels:
      app: binary-mirror
  template:
    metadata:
      labels:
        app: binary-mirror
    spec:
      containers:
      - name: service
        image: localhost/local-dev/dams-binary-mirror:sandbox
        imagePullPolicy: Never
        volumeMounts:
        - name: env-config
          mountPath: /etc/fin/.env
          subPath: .env
        env:
        - name: FIN_SERVICE_NAME
          value: "mirror-rsync"
        - name: FCREPO_HOST
          value: "http://dams.local:3000"
        - name: SERVICE_ACCOUNT_NAME
          value: "binary-mirror-service-account"
        - name: SERVICE_ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              name: binary-mirror-service-account-key
              key: secret
        - name: MESSAGE_SECRET
          valueFrom:
            secretKeyRef:
              name: binary-mirror-message-key
              key: secret
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: env-config
        secret:
          secretName: env-config