apiVersion: v1
kind: Service
metadata:
  name: binary-mirror
spec:
  type: ClusterIP
  selector:
    app: binary-mirror
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000