apiVersion: batch/v1
kind: Job
metadata:
  name: import-pioneering-punjabis
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: pioneering-punjabis
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-pioneering-punjabis-volume-claim