apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fcrepo
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/fin-fcrepo:2.12.0
      volumes:
        - name: ocfl-volume
          persistentVolumeClaim:
            claimName: ocfl-volume-claim
  volumeClaimTemplates:
    - metadata:
        name: activemq-volume
      spec:
        storageClassName: nfs-csi
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi