apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/fin-base-service:local-dev
          env:
          - name: K8S_ENABLED
            value: "true"
          - name : "K8S_PLATFORM"
            value: "docker-desktop"
          - name: "K8S_NAMESPACE"
            value: "dams"
