apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: import-green-papers
spec:
  selector:
    matchLabels:
      app: import-green-papers
  template:
    metadata:
      labels:
        app: import-green-papers
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi