apiVersion: batch/v1
kind: Job
metadata:
  name: import-eastman
spec:
  selector:
    matchLabels:
      app: import-eastman
  template:
    metadata:
      labels:
        app: import-eastman
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: eastman
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 70Gi