apiVersion: batch/v1
kind: Job
metadata:
  name: import-mudd-mapes
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: mudd-mapes
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-mudd-mapes-volume-claim