apiVersion: batch/v1
kind: Job
metadata:
  name: import-picnic-day
spec:
  template:
    spec:
      containers:
      - name: importer
        env:
          - name: COLLECTION_NAME
            value: Picnic_Day
        volumeMounts:
        - name: import-volume
          mountPath: /data
      volumes:
      - name: import-volume
        persistentVolumeClaim:
          claimName: import-picnic-day-volume-claim