apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/ucdlib-dams/pub/dams-iipimage-server:2.6.7
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          env:
            - name: USE_LOCAL_GCSFUSE
              value: 'true'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/fin/service-account.json
            - name: GCS_BUCKET
              value: dams-client-media-prod
