apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif
spec:
  template:
    spec:
      containers:
        - name: service
          image: gcr.io/ucdlib-pubreg/dams-iipimage-server:dev
      serviceAccountName: dams-production